# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  dependsOn: []
  displayName: 'This is Stage A'
  jobs: 
  - job: A1
    dependsOn: A2
    steps:
    - bash: echo "Job 1"
  - job: A2
    steps:
    - bash: echo "Job 2"

- stage: Deploy
  dependsOn: []
  displayName: 'This is stage B'
  jobs:
  - job: B1
    steps: 
    - bash: echo "Job B1"
    
  - job: B2
    steps: 
    - bash: echo "Job B2"

